theme: jekyll-theme-minimal
title: mir A. Nasrollahzadeh
description: [Here, I am sharing snippets of the projects I am working on in Operations Research or Machine Learning.]
logo: [Location of the logo]
show_downloads: "false"
google_analytics: [Your Google Analytics tracking ID]
