title: Amir A. Nasrollahzadeh
logo: /assets/amir_zadeh-removebg-preview.png
description: Here, I am sharing snippets of the projects I am working on in Operations Research or Machine Learning.
show_downloads: "false"
google_analytics: UA-174038662-1
theme: jekyll-theme-minimal
